[DEFAULT]
pristine-tar=True
upstream-vcs-tag=gpgmeqt-%(version)s
debian-branch = gnupg/stable

[import-orig]
filter = [
 'VERSION',
 '*~',
 '*/*~',
 '*/*/*~',
 '*/*/*/*~',
 '*/*/*/*/*~',
 ]
filter-pristine-tar = False
